---
title: "v_ARG_plasmids"
author: "Kate Bowie"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: kate
    toc: TRUE
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Libraries
```{r}

library(ggplot2)
library(readxl)
library(here)
library(tidyverse)
library(patchwork)
library(readr)
library(phyloseq)
library(microshades)
library(ggtree)
library(ape)
library(pheatmap)
library(vegan)
library(ggpubr)
library(rstatix)
library(cowplot)
library(RColorBrewer)
library(viridis)
library(ggalluvial)
library(ggplotify)

```


# load data
```{r}

arg_db <- read_tsv(file = here("Data", "plasmid_ARGs.tsv"), col_names = TRUE)
meta <- read_csv(file = here("Data", "meta_deidentified.csv"), col_names = TRUE)
cov_map <- read_tsv(file = here("Data", "plasmid_contig_coverage.tsv"), col_names = TRUE)
seq_meta <- read_excel(here("Data", "pb_metadata_deidentified.xlsx"), col_names = TRUE)
plas_db <- read_tsv(file = here("Data", "plasmid_scores.tsv"), col_names = TRUE)


```



# cleaning up
```{r}

meta$sample_name <- meta$sample_id
meta <- meta %>% 
  select(sample_name, room, day, room_type, before_after) %>% 
  unique()

arg_db <- arg_db %>% 
  mutate(old_contig = contig_id) %>% 
  select(-(contig_id), -(Nudged), -(Other_SNPs), -(SNPs_in_Best_Hit_ARO), -(Hit_Start), -(Hit_End), -(Note), -(extra_info), -(Contig), -(Start), -(Stop), -(Orientation), -(Predicted_DNA))


arg_db <- arg_db %>% 
  mutate(contig = str_remove(old_contig, "_\\d+$"), 
         ARG_length = stop - start)

plas_db <- plas_db %>% 
  filter(final_type == "plasmid")


```



# combine things!
```{r}

test <- merge(arg_db, plas_db, by = c("sample", "contig"), all = TRUE)
test_2 <- merge(test, cov_map, by = c("sample", "contig"), all.x = TRUE)

test <- test_2 %>% 
  mutate(barcode = sample) %>% 
  select(-(sample))

full_meta <- merge(seq_meta, meta, by = "sample_name")

rm(arg_db, cov_map, seq_meta, meta, test_2, plas_db)

```


# adding in label
```{r}

df <- merge(test, full_meta, by = "barcode")

df <- df %>% 
  mutate(Best_Hit_ARO = ifelse(is.na(Best_Hit_ARO), "none", Best_Hit_ARO)) %>% 
  mutate(ARG_length = ifelse(is.na(ARG_length), 0, ARG_length))


remove(test, full_meta)


```


# removing binned contigs
I learned that some of these contigs were later used to fill in bins, so I am filtering those out to not count them incorrectly.
```{r}

binned_c <- read_tsv(file = here("Data", "Final_MAGs_contigs_list.tsv"), col_names = TRUE)

binned_c <- binned_c %>% 
  mutate(barcode = sample)

df_filt <- anti_join(df, binned_c, by = c("barcode", "contig"))
df_all <- df_filt

rm(binned_c, df_filt,  df)  

```



```{r}

# adding abundance and rpk
df <- df_all %>%
  filter(final_type == "plasmid") %>% 
  group_by(sample_name) %>% 
  mutate(total_contig_reads = sum(length*coverage)) %>% 
  ungroup() %>% 
  group_by(sample_name, Best_Hit_ARO, final_type) %>% 
  mutate(ARG_rel_abund = (ARG_length * coverage)/total_contig_reads)



df <- df %>% 
  mutate(growth = case_when(
    before_after == "before" ~ "before",
    before_after == "after" ~ "regrowth"
  ))

```


# Number of plasmids
```{r}

p_count <- df %>% 
  filter(plasflow_type == "plasmid") %>% 
  select(sample_name, growth, contig, room_type, room) %>% 
  distinct() %>% 
  group_by(growth, sample_name, room_type, room) %>% 
  summarise(count = n()) %>% 
  ungroup()

p_count %>% 
  summarize(median_p = median(count), 
            q1 = quantile(count, 0.25, na.rm = TRUE),
            q3 = quantile(count, 0.75, na.rm = TRUE))


plasmid_count <- p_count %>% 
  ggplot(., aes(x = growth, y = count)) + 
  geom_boxplot() + 
  geom_jitter() +
  theme_bw() + 
  xlab("") + ylab("Number of Plasmids") + ylim(0, 1400)


# non-normal
shapiro_test(p_count$count)

paired_df <- p_count %>%
  select(growth, count, room) %>% 
  pivot_wider(names_from = growth, values_from = count)

wilcox.test(paired_df$before, paired_df$regrowth, paired = TRUE)

stat.test <- p_count %>% 
  pairwise_wilcox_test(count ~ growth, p.adjust.method = "fdr") %>%
  mutate(y.position = 1300)

plasmid_count <- plasmid_count + stat_pvalue_manual(stat.test, label = "p.adj.signif") +
  coord_cartesian(clip = "off")


plasmid_counts <- df %>% 
  filter(plasflow_type == "plasmid") %>% 
  select(sample_name, growth, contig, room_type) %>% 
  distinct() %>% 
  group_by(growth, sample_name, room_type) %>% 
  summarise(count = n())

ggplot(plasmid_counts, aes(x = growth, y = count, fill = room_type)) + 
  geom_boxplot() + 
  theme_bw() + 
  xlab("") + ylab("Number of Plasmids")

p <- ggplot(plasmid_counts, aes(x = growth, y = count, fill = room_type)) +
  geom_boxplot() +
  theme_bw() +
  xlab("") +
  ylab("Number of Plasmids") +
  scale_fill_manual(values = c("hallway" = "#1f77b4", "patient" = "#ff7f0e"))

# Add paired Wilcoxon p-values per room type
p + stat_compare_means(aes(group = growth),
                       method = "wilcox.test",
                       paired = TRUE,
                       label = "p.signif",
                       comparisons = list(c("before", "regrowth")),
                       ref.group = NULL) +
  facet_wrap(~room_type)

```



```{r}

df %>% 
  filter(plasflow_type == "plasmid") %>%  
  filter(Best_Hit_ARO != "none") %>% 
  select(sample_name, growth, contig, room_type) %>% 
  distinct() %>% 
  group_by(growth, sample_name, room_type) %>% 
  summarise(count = n()) %>% 
  ggplot(., aes(x = growth, y = count)) + 
  geom_boxplot() + theme_bw() + 
  xlab("") + ylab("Number of Plasmids with ARGs") + facet_wrap(~room_type)

```


```{r}

df %>% 
  mutate(contig_rel_abund = (length * coverage)/total_contig_reads,
         ARG_rel_abund2 = ARG_length * contig_rel_abund) %>% 
  filter(final_type == "plasmid") %>%  
  filter(Best_Hit_ARO != "none") %>% 
  filter(map_lgl(`Drug Class`, ~ any(str_detect(.x, "carbapenem")))) %>% 
  select(sample_name, contig, Best_Hit_ARO, growth, room, room_type) %>% 
  distinct() %>% 
  group_by(sample_name, contig, Best_Hit_ARO, growth, room, room_type) %>% 
  summarise(count = n()) %>% 
  ggplot(., aes(x = growth, y = count, fill = Best_Hit_ARO)) + 
  geom_col() + theme_bw() + 
  facet_wrap(~room, scales = "free_y") +
  xlab("")

```


# proportion of carb plasmids
```{r}

carb_summary <- df %>%
  #filter(Best_Hit_ARO != "none") %>% 
  filter(final_type == "plasmid") %>% 
  group_by(growth, room_type, room) %>%
  summarise(
    total_plasmids = n_distinct(contig),
    carb_plasmids = n_distinct(contig[Best_Hit_ARO != "none" & 
                       map_lgl(`Drug Class`, ~ any(str_detect(.x, "carbapenem")))])) %>%
  mutate(prop_carb_plasmids = (carb_plasmids / total_plasmids)*100) %>% ungroup()


ggplot(carb_summary, aes(x = growth, y = prop_carb_plasmids)) + 
  geom_boxplot() + theme_bw() + 
  ylab("Proportion of Plasmids \nwith Carbapenem") + xlab("") +
  facet_wrap(~room_type)

prop_carb <- ggplot(carb_summary, aes(x = growth, y = prop_carb_plasmids)) + 
  geom_boxplot() + 
  geom_jitter() +
  theme_bw() + 
  ylab("Proportion of Plasmids \nwith Carbapenemases") + xlab("") +
  ylim(0,1.4)




paired_df <- carb_summary %>%
  select(growth, prop_carb_plasmids, room) %>% 
  pivot_wider(names_from = growth, values_from = prop_carb_plasmids)

stat.test <- carb_summary %>%
  pairwise_wilcox_test(prop_carb_plasmids ~ growth, paired = TRUE, p.adjust.method = "fdr") %>%
  mutate(y.position = 1.3)

prop_carb <- prop_carb + stat_pvalue_manual(stat.test, label = "p.adj.signif") +
  coord_cartesian(clip = "off")




```



# abundance
```{r}

carb_abund_summary <- df %>% 
  filter(Best_Hit_ARO != "none") %>% 
  filter(plasflow_type == "plasmid") %>% 
  mutate(contig_rel_abund = (length * coverage)/total_contig_reads,
         ARG_rel_abund2 = ARG_length * contig_rel_abund) %>% 
  #distinct() %>% 
  group_by(growth, room) %>%
  summarise(
    total_plasmids = sum(contig_rel_abund),
    carb_plasmids = sum(contig_rel_abund[Best_Hit_ARO != "none" & 
                       map_lgl(`Drug Class`, ~ any(str_detect(.x, "carbapenem")))])) %>%
  mutate(prop_carb_plasmids = (carb_plasmids / total_plasmids)*100)

ggplot(carb_abund_summary, aes(x = growth, y = prop_carb_plasmids)) + 
  geom_boxplot() + theme_bw()


paired_df <- carb_abund_summary %>%
  select(growth, prop_carb_plasmids, room) %>% 
  pivot_wider(names_from = growth, values_from = prop_carb_plasmids)

# Non-parametric paired test
wilcox.test(paired_df$before, paired_df$regrowth, paired = TRUE)

```



```{r}

df %>% 
  filter(map_lgl(`Drug Class`, ~ any(str_detect(.x, "carbapenem")))) %>% 
  select(Best_Hit_ARO) %>% 
  unique()

```

# saving
```{r}

boxplots <- plot_grid(plasmid_count, prop_carb, labels = c("F", "G"), nrow = 2, label_x = 0.005)
rm(list = setdiff(ls(), c("plasmid_count", "prop_carb")))

save.image(file = here("Data", "plasmid_boxplot.RData"))


```



