---
title: "v_shortread_ARGs"
author: "Kate Bowie"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: kate
    toc: TRUE
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Libraries
```{r}

library(ggplot2)
library(readxl)
library(here)
library(tidyverse)
library(patchwork)
library(readr)
library(phyloseq)
library(microshades)
library(ape)
library(pheatmap)
library(RColorBrewer)
library(viridis)
library(vegan)
library(rstatix)
library(ggpubr)
library(cowplot)

```



# load data
```{r}

amr_df <- read_csv(file = here("Data", "SR_merged_AMR_deidentified.csv"), col_names = TRUE)

load(here("Data", "shortread_ps.RData"))
meta <- data.frame(ps_decon@sam_data)
rm(ps_clean)

```


# merging/cleaning
```{r}

amr_df$new_id <- gsub("_", ".", amr_df$Sample_Name_y)

amr_clean <- merge(meta, amr_df, by = "new_id")

amr_clean <- amr_clean %>% 
  select(-(ORF_ID))

```



# Adding RPKM
```{r}

amr_clean$RPKM <- (amr_clean$ARG_Reads * 1e9) / (amr_clean$ARG_Length * amr_clean$SampleSums)

total_rpkm <- amr_clean %>% 
  group_by(new_id) %>% 
  summarise(total_RPKM = sum(RPKM), total_reads = sum(ARG_Reads))

amr_clean <- merge(amr_clean, total_rpkm, by = "new_id")

rm(total_rpkm)

amr_treated <- amr_clean %>% 
  filter(!(sample_type %in% c("untreated", "neg", "mc"))) %>% 
  filter(growth != "NA" & room_type != "untreated")

```


# Most abundant ARGs
```{r}

top_args <- amr_treated %>% 
  select(Best_Hit_ARO, RPKM, AMR_Gene_Family) %>% 
  group_by(Best_Hit_ARO, AMR_Gene_Family) %>% 
  summarise(sum_arg = sum(RPKM)) %>% 
  arrange(desc(sum_arg))

```



# Overall RPKM boxplots by growth
```{r}

rpkm_stats <- amr_treated %>% 
  select(new_id, total_RPKM, growth, total_reads, room_type) %>% 
  group_by(new_id) %>% 
  unique() %>% 
  ungroup()


rpkm_stats %>% 
  summarise(med_rpkm = median(total_RPKM), 
            Q1 = quantile(total_RPKM, probs = 0.25, na.rm = TRUE),
            Q3 = quantile(total_RPKM, probs = 0.75, na.rm = TRUE))

rpkm_stats %>% 
  group_by(growth) %>% 
  summarise(med_rpkm = median(total_RPKM), 
            Q1 = quantile(total_RPKM, probs = 0.25, na.rm = TRUE),
            Q3 = quantile(total_RPKM, probs = 0.75, na.rm = TRUE))


sr_arg <- rpkm_stats %>% 
  ggplot(., aes(x = growth, y = total_RPKM)) + 
  geom_boxplot() +
  theme_bw() +
  xlab("") + ylab("RPKM")

# non-normal
shapiro_test(rpkm_stats$total_RPKM)

kruskal.test(total_RPKM ~ growth, data = rpkm_stats)
pairwise.wilcox.test(rpkm_stats$total_RPKM, rpkm_stats$growth, p.adjust.method = "fdr")


# plot
stat.test <- rpkm_stats %>%
  mutate(growth = droplevels(growth)) %>% 
  pairwise_wilcox_test(total_RPKM ~ growth,
    p.adjust.method = "fdr")

rpkm_sr_plot <- sr_arg + stat_pvalue_manual(stat.test, label = "p.adj", y.position = c(9700, 11500, 13000))


```


### reads
```{r}

rpkm_stats %>% 
  summarise(med_rpkm = median(total_reads), 
            Q1 = quantile(total_reads, probs = 0.25, na.rm = TRUE),
            Q3 = quantile(total_reads, probs = 0.75, na.rm = TRUE))


sr_arg <- rpkm_stats %>% 
  ggplot(., aes(x = growth, y = total_reads)) + 
  geom_boxplot() +
  theme_bw() +
  xlab("") + ylab("Reads")

# non-normal
shapiro_test(rpkm_stats$total_reads)

kruskal.test(total_reads~ growth, data = rpkm_stats)
pairwise.wilcox.test(rpkm_stats$total_reads, rpkm_stats$growth, p.adjust.method = "fdr")


# plot
stat.test <- rpkm_stats %>%
  mutate(growth = droplevels(growth)) %>% 
  pairwise_wilcox_test(total_reads ~ growth,
    p.adjust.method = "fdr")

arg_read_plot <- sr_arg + stat_pvalue_manual(stat.test, label = "p.adj", y.position = c(450000, 500000, 550000))

```



# Carb only
```{r}

total_rpkm <- amr_clean %>% 
  filter(map_lgl(`Drug Class`, ~ any(str_detect(.x, "carbapenem")))) %>% 
  group_by(new_id) %>% 
  summarise(carb_RPKM = sum(RPKM))

amr_clean <- merge(amr_clean, total_rpkm, by = "new_id")

rm(total_rpkm)

amr_treated <- amr_clean %>% 
  filter(sample_type != c("untreated", "neg", "mc")) %>% 
  filter(growth != "NA" & room_type != "untreated")

rpkm_stats <- amr_treated %>% 
  select(new_id, carb_RPKM, growth) %>% 
  group_by(new_id) %>% 
  unique() %>% 
  ungroup()


rpkm_stats %>% 
  summarise(med_rpkm = median(carb_RPKM), 
            Q1 = quantile(carb_RPKM, probs = 0.25, na.rm = TRUE),
            Q3 = quantile(carb_RPKM, probs = 0.75, na.rm = TRUE))


sr_arg <- rpkm_stats %>% 
  ggplot(., aes(x = growth, y = carb_RPKM)) + 
  geom_boxplot() +
  theme_bw() +
  xlab("") + ylab("RPKM")

# non-normal
shapiro_test(rpkm_stats$carb_RPKM)

kruskal.test(carb_RPKM ~ growth, data = rpkm_stats)
pairwise.wilcox.test(rpkm_stats$carb_RPKM, rpkm_stats$growth, p.adjust.method = "fdr")


# plot
stat.test <- rpkm_stats %>%
  mutate(growth = droplevels(growth)) %>% 
  pairwise_wilcox_test(carb_RPKM ~ growth,
    p.adjust.method = "fdr")

rpkm_sr_plot_carb <- sr_arg + stat_pvalue_manual(stat.test, label = "p.adj", y.position = c(1300, 1500, 1700))

```


# Mechanism
```{r}

amr_treated %>% 
  select(`Resistance Mechanism`, carb_RPKM, growth) %>% 
  group_by(growth, `Resistance Mechanism`) %>% 
  summarise(res_sum = sum(carb_RPKM)) %>% 
  ggplot(., aes(x = growth, y = res_sum, fill = `Resistance Mechanism`)) +
  scale_y_log10() +
  geom_col()


amr_treated %>% 
  select(`Resistance Mechanism`, carb_RPKM, growth) %>% 
  group_by(growth, `Resistance Mechanism`) %>% 
  summarise(res_sum = sum(carb_RPKM)) %>% 
  ggplot(., aes(x = growth, y = res_sum, fill = `Resistance Mechanism`)) +
  geom_col()

```

### Efflux pumps
```{r}


rmech <- amr_treated %>% 
  mutate(Resistance_Mech = str_split(`Resistance Mechanism`, "; ")) %>% 
  unnest(Resistance_Mech) %>% 
  mutate(Resistance_Mechanisms = str_trim(Resistance_Mech)) %>% 
  select(Resistance_Mech, growth, Best_Hit_ARO, sample_id, RPKM) %>% 
  unique()



rmech %>% 
  select(Resistance_Mech, growth, RPKM) %>% 
  group_by(growth, Resistance_Mech) %>% 
  unique() %>% 
  summarise(res_sum = sum(RPKM)) %>% 
  ggplot(., aes(x = growth, y = res_sum, fill = Resistance_Mech)) +
  geom_col() + theme_bw()


ef_pumps <- rmech %>% 
  select(Resistance_Mech, growth, RPKM, sample_id) %>% 
  group_by(growth, sample_id, Resistance_Mech) %>% 
  unique() %>% 
  summarise(res_sum = sum(RPKM)) %>% 
  filter(Resistance_Mech == "antibiotic efflux") %>% 
  ggplot(., aes(x = growth, y = res_sum)) +
  geom_boxplot() + theme_bw() +
  ylab("RPKM") + xlab("")

```


```{r}

# plot
stat.test <- rmech %>%
  filter(Resistance_Mech == "antibiotic efflux") %>%
  select(Resistance_Mech, growth, RPKM, sample_id) %>%
  group_by(growth, sample_id, Resistance_Mech) %>%
  summarise(res_sum = sum(RPKM), .groups = "drop") %>%
  mutate(growth = droplevels(growth)) %>% 
  pairwise_wilcox_test(res_sum ~ growth, p.adjust.method = "fdr")


rpkm_efflux <- ef_pumps + stat_pvalue_manual(stat.test, label = "p.adj.signif", y.position = c(8000, 9500, 11000))


```



# ARG categories over time
```{r}

# Define resistance mechanism categories
df <- rmech %>%
  mutate(category = case_when(
    # Carbapenemases (e.g. OXA, GES, AIM, NDM, KPC, IMP, VIM, GOB, BlaB, etc.)
    str_detect(Best_Hit_ARO, regex("OXA|GES|AIM|NDM|KPC|IMP|VIM|GOB|BlaB|CIM|BJP|IND|CME|CGB|SRT|LEN|OXY|PAU|PRC", ignore_case = TRUE)) ~ "Carbapenemase",
    str_detect(Best_Hit_ARO, regex("ade|acr|mex|sme|emr|mdt|oqx|abe|amv|bcr|cmx|mdf|mdt|mdr|Mux|Opr|Opm|Axy|Tri|sdrM", ignore_case = TRUE)) ~ "Efflux pump",
    str_detect(Best_Hit_ARO, regex("Fos|fos|GlpT|UhpT", ignore_case = TRUE)) ~ "Fosfomycin resistance",
    str_detect(Best_Hit_ARO, regex("qac", ignore_case = TRUE)) ~ "QAC resistance",
    str_detect(Best_Hit_ARO, regex("TEM|SHV|CTX|CMY|ACT|DHA|MIR|ACC|PDC", ignore_case = TRUE)) ~ "ESBL/AmpC",
    str_detect(Best_Hit_ARO, regex("AAC|ANT|APH|aad", ignore_case = TRUE)) ~ "Aminoglycoside resistance",
    str_detect(Best_Hit_ARO, regex("van", ignore_case = TRUE)) ~ "Vancomycin/glycopeptide resistance",
    str_detect(Best_Hit_ARO, regex("erm|lnu|lsa|msr|vga|mph", ignore_case = TRUE)) ~ "MLS resistance",
    str_detect(Best_Hit_ARO, regex("tet", ignore_case = TRUE)) ~ "Tetracycline resistance",
    str_detect(Best_Hit_ARO, regex("qnr|gyr|par", ignore_case = TRUE)) ~ "Fluoroquinolone resistance",
    TRUE ~ "Other/Unclassified"))


df %>% 
  select(category, growth, RPKM, sample_id) %>% 
  group_by(growth, sample_id, category) %>% 
  unique() %>% 
  summarise(res_sum = sum(RPKM)) %>% 
  ggplot(., aes(x = growth, y = res_sum)) +
  geom_boxplot() + theme_bw() + ggtitle("ARG Categories") +
  ylab("RPKM") +
  facet_wrap(~category, scales = "free")



```


# Per room
## Number of different ARGs?
```{r}

arg_richness <- amr_treated %>%
  group_by(room, growth) %>%
  summarise(ARG_count = n_distinct(Best_Hit_ARO))

ggplot(arg_richness, aes(x = growth, y = ARG_count)) +
  geom_boxplot() +
  theme_minimal()


# carbapenem only
arg_richness <- amr_treated %>%
  filter(map_lgl(`Drug Class`, ~ any(str_detect(.x, "carbapenem")))) %>%
  group_by(room, growth) %>%
  summarise(ARG_count = n_distinct(Best_Hit_ARO))

ggplot(arg_richness, aes(x = growth, y = ARG_count)) +
  geom_boxplot() +
  theme_minimal()

```


## RPKM per room
```{r}

arg_total_rpkm <- amr_treated %>%
  group_by(room, growth) %>%
  summarise(Total_RPKM = sum(RPKM))

ggplot(arg_total_rpkm, aes(x = growth, y = Total_RPKM)) +
  geom_boxplot() +
  theme_minimal() + ylab("ARG RPKM") + xlab("")


```


## Drug Class
```{r}

class_rpkm <- amr_treated %>%
  group_by(room, growth) %>%
  summarise(Class_count = n_distinct(`Drug Class`))

ggplot(class_rpkm, aes(x = growth, y = Class_count)) +
  geom_boxplot() +
  theme_minimal()

```



# Diversity of ARGs
```{r}
# need to pivot my dataframe first
arg_wide <- amr_treated %>%
  group_by(new_id, Best_Hit_ARO) %>%
  summarise(RPKM = sum(RPKM), .groups = "drop") %>%  # sum duplicates
  select(Best_Hit_ARO, new_id, RPKM) %>% 
  pivot_wider(names_from = Best_Hit_ARO, values_from = RPKM, values_fill = 0) %>% 
  column_to_rownames("new_id") %>% 
  mutate(across(everything(), as.numeric))

shannon_div <- diversity(arg_wide, index = "shannon")

# Simpson diversity
simpson_div <- diversity(arg_wide, index = "invsimpson")

# Combine with metadata
arg_diversity_df <- data.frame(new_id = rownames(arg_wide), Shannon = shannon_div,Simpson = simpson_div)

arg_div <- merge(amr_clean, arg_diversity_df, by = "new_id")

Simpson <- arg_div %>% 
  filter(growth != "NA") %>% 
  filter(!(is.na(growth))) %>% 
  filter(room_type != "untreated") %>% 
  ggplot(., aes(x = growth, y = Simpson)) + 
  theme_bw() +
  geom_boxplot() + 
  ylab("Inverse Simpson") + xlab("")

Shannon <- arg_div %>% 
  filter(growth != "NA") %>% 
  filter(!(is.na(growth))) %>% 
  filter(room_type != "untreated") %>% 
  ggplot(., aes(x = growth, y = Shannon)) + 
  geom_boxplot() + 
  theme_bw() + xlab("")

plot_grid(arg_read_plot, Shannon, Simpson, labels = c("A", "B", "C"), nrow = 1)

```





# Saving plot
```{r}

rm(list = setdiff(ls(), c("rpkm_sr_plot")))

save.image(file = here("Data", "rpkm_plot.RData"))

```

